before:
  hooks:
    - go work sync

dist: bin 
 
project_name: odict

git:
  ignore_tags:
    - js-*
    - python-*
    - jvm-*

builds:
  - id: odict
    main: ./odict.go
    ldflags:
      - -X 'github.com/TheOpenDictionary/odict/cli.version={{.Version}}'
    goos:
      - linux
      - darwin
      - windows 
  - id: single
    main: ./odict.go
    binary: odict
    ldflags:
      - -X 'github.com/TheOpenDictionary/odict/cli.version={{.Version}}'
    no_unique_dist_dir: true

archives:
  - builds:
      - odict
      
brews:
  - name: odict
    homepage: "https://odict.org/"
    description: "A lightning-fast dictionary compiler and toolchain"
    folder: Formula
    repository:
      owner: TheOpenDictionary
      name: homebrew-odict