insta = "cargo insta"
run = "cargo run -p cli"

[clean]
depends = ["clean:*"]
run = "rm -rf **/*.odict"

[test]
depends = ["test:*"]

[setup]
run = ["mise install", "corepack enable", "pnpm install --no-frozen-lockfile"]

["build-all"]
depends = ["build:*"]

["default"]
run = "mise run build"
