["clean:java"]
run = "gradle clean"
dir = "bindings/java"

["build:java"]
run = "gradle assemble"
dir = "bindings/java"
depends = ["build:cli"]

["test:java"]
dir = "bindings/java"
run = ["RUNTIME_ENV=test gradle test --info", "gradle clean"]
depends = ["build:cli"]
