["clean:java"]
run = "./gradlew clean"
dir = "bindings/java"

["build:java"]
run = "./gradlew build"
dir = "bindings/java"
depends = ["build:cli"]

["test:java"]
dir = "bindings/java"
run = ["RUNTIME_ENV=test ./gradlew test --info", "./gradlew clean"]
depends = ["build:cli"]
