["clean:java"]
run = "./gradlew clean"
dir = "bindings/java"

["build:java"]
run = "./gradlew build"
dir = "bindings/java"
depends = ["build:lib"]

["test:java"]
dir = "bindings/java"
run = ["RUNTIME_ENV=test ./gradlew test --info", "mise task run clean:java"]
depends = ["build:lib"]
