["build:node"]
run = "pnpm --filter=\"@odict/node\" build"

["publish:node"]
run = "pnpm --filter=\"@odict/node\" npm publish"

["test:node"]
run = "pnpm --filter=\"@odict/node\" test -- "
depends = ["build:node"]

["ci:node"]
run = "act napi --container-architecture linux/amd64 --bind --job build"
hide = true

["clean:node"]
run = "rm -rf dist"
