name: Go

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version number'     
        required: true
      changes:
        description: 'Description of changes'
        required: true

env:
  GO_VERSION: "^1.18"
  JAVA_VERSION: 11

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Bazelisk
        run: |
          go get github.com/bazelbuild/bazelisk
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.MAVEN_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Deploy to Maven
        run: bazelisk run --stamp --define "maven_repo=https://oss.sonatype.org/service/local/staging/deploy/maven2" --define "maven_user={{ secrets.MAVEN_USERNAME }}" --define "maven_password={{ secrets.MAVEN_PASSWORD }}" --define gpg_sign=true //java/main/java/org/odict:odict.publish
